Repository prgrms-web-devcourse/team-7sung-heycake-fe, pull requests merged in 2023-03, with the labels that each got.

#61 feat: 업체 상세 페이지를 실제 데이터와 연결한다
  components/Api/getCakeList.ts
  components/Api/getMarketDetail.ts
  components/Api/getMarketList.ts
  components/Api/index.tsx
  components/Main/cakeList.tsx
  components/Market/marketProfile.tsx
  next.config.js
  pages/api/enrollments/[id].tsx
Labels: 프론트, feat

#64 feat: order api
  .eslintignore
  .gitignore
  next.config.mjs
  pages/orders/[id].tsx
  types/orders.ts
Labels: 프론트, feat

#71 feat: 주문 생성
  pages/orders/new.tsx
Labels: 프론트, feat

#69 feat: 마이페이지(업체 정보 등록) validation 추가
  components/Mypage/enrollmentForm.tsx
  constants/errorMessages.ts
Labels: 프론트, feat

#68 feat: 메인페이지의 통신과 구현을 완성한다
  components/Header/index.tsx
  components/Main/cakeItem.tsx
  components/Main/cakeList.tsx
  components/Main/constants.ts
  pages/api/orders.tsx
Labels: feat

#73 feat: 업체 정보 등록 api
  components/Api/postEnrollment.ts
  components/Mypage/enrollmentForm.tsx
  pages/index.tsx
Labels: 프론트, feat

#79 feat: 비로그인 메인 페이지 진입 기능
  pages/index.tsx
Labels: 프론트, feat

#83 feat: 디자인 및 입력값 전반적인 수정
  components/Admin/marketItem.tsx
  components/Admin/marketList.tsx
  components/Admin/numberWithHyphen.ts
  components/Admin/types.ts
  components/Api/types.ts
  components/Main/cake/cakeItem.tsx
  components/Main/constants.ts
  components/Main/numberWithCommas.ts
Labels: feat

#82 feat: thread api 연동
  components/Orders/Thread.tsx
  pages/orders/[id].tsx
  types/orders.ts
Labels: 프론트, feat

#88 feat: 상세페이지 사진 개발 및 쓰레드 연동
  components/Orders/ImageSlider.tsx
  components/Orders/Thread.tsx
  components/Orders/index.ts
  pages/orders/[id].tsx
  types/orders.ts
Labels: 프론트, feat

#87 feat: 반응형 디자인에 따른 UI/UX 수정
  components/Admin/index.tsx
  components/Admin/marketItem.tsx
  components/Header/index.tsx
  components/Main/cake/cakeMain.tsx
  components/Main/location/locationListItem.tsx
Labels: feat

#89 feat: 메인 페이지에 새 글 버튼 생성
  components/Main/cake/cakeItem.tsx
  components/Main/cake/cakeMain.tsx
Labels: feat

#90 feat: 상세페이지 리액트쿼리 마이그레이션 및 유틸함수 개발
  components/Orders/ImageSlider.tsx
  components/Orders/Thread.tsx
  pages/orders/[id].tsx
  utils/orders.ts
Labels: 프론트, feat, refactor

#91 feat: 로그인 성공 시, api 연동
  pages/api/users/kakao-login.ts
  pages/index.tsx
  pages/main.tsx
Labels: 프론트, feat

#93 feat: 업체 선택 개발
  components/Orders/Thread.tsx
  pages/orders/[id].tsx
Labels: 프론트, feat

#94 feat: 메인페이지 , 업체 신청 리스트 무한스크롤
  components/Admin/marketItem.tsx
  components/Admin/marketList.tsx
  components/Api/Main.ts
  components/Api/types.ts
  components/Main/cake/cakeList.tsx
  pages/api/enrollments/index.tsx
  pages/api/orders.tsx
Labels: feat

#98 refactor: thread 관심사 분리
  .eslintrc.json
  components/Orders/Thread.tsx
  hooks/useSelectOffer.ts
  pages/orders/[id].tsx
  public/.empty
  styles/.empty
Labels: 프론트, refactor

#100 refactor: 타입 정의 후 chakra ui radio 적용, 주문 생성 페이지
  pages/orders/new.tsx
  types/orders.ts
  utils/orders.ts
Labels: 프론트, refactor

#101 feat: 업체 정보 등록 완료 페이지 구현
  components/Mypage/enrollmentForm.tsx
  components/Mypage/enrollmentInfo.tsx
  components/Mypage/mypageTitle.tsx
  pages/index.tsx
  pages/mypage/enrollment/index.tsx
  pages/mypage/enrollment/success/index.tsx
Labels: 프론트, feat

#103 feat: 주문 생성 이미지 드래그앤드랍
  hooks/useImageUpload.ts
  pages/orders/new.tsx
Labels: 프론트, feat

#104 feat: 주문 생성
  components/Orders/CakeSelect.tsx
  constants/cakeFormat.ts
  constants/errorMessages.ts
  hooks/useClickInput.ts
  package-lock.json
  package.json
  pages/orders/new.tsx
  types/orders.ts
Labels: 프론트, feat

#102 fix: 배포전 사용성 개선
  components/Admin/adminLIstSkeleton.tsx
  components/Admin/login.tsx
  components/Api/Main.ts
  components/Header/index.tsx
  components/Main/cake/cakeItem.tsx
  components/Main/cake/cakeList.tsx
  components/Main/cake/cakeListSkeleton.tsx
  components/Main/cake/cakeMain.tsx
  components/Main/constants.ts
  components/Main/location/locationSelectBox.tsx
  components/Main/types.ts
  pages/admin/login.tsx
  public/images/sampleCake.jpg
Labels: 프론트, feat, refactor, fix

#106 refactor: global 수정
  .eslintrc.json
  components/Admin/index.tsx
  components/Admin/marketList.tsx
  components/Header/index.tsx
  components/Layout/layout.tsx
  components/Main/cake/cakeList.tsx
  components/Main/cake/cakeMain.tsx
  pages/_app.tsx
  pages/index.tsx
  pages/orders/new.tsx
  styles/font.css
Labels: 프론트, feat, refactor

#108 feat: chakra custom 및 new order 사진 제한 개발
  components/Main/cake/cakeMain.tsx
  components/Main/location/locationSelectBox.tsx
  hooks/useImageUpload.ts
  pages/orders/new.tsx
  public/theme/theme.ts
  types/orders.ts
Labels: 프론트, feat, refactor, fix

#109 feat: 주문 추가 디테일 개선
  constants/cakeFormat.ts
  pages/orders/new.tsx
  types/orders.ts
  utils/orders.ts
Labels: 프론트, feat, refactor, fix

#112 feat: market page link 연동
  components/Orders/Thread.tsx
Labels: 프론트, feat

#114 feat: scrollbar none
  pages/_app.tsx
  styles/style.css
Labels: 프론트, feat

#116 feat: decode util func
  package-lock.json
  package.json
  utils/getMemberIdFromToken.ts
Labels: 프론트, feat

#118 refactor: ssr 이용, useQuery remove
  pages/orders/[id]/index.tsx
Labels: 프론트, refactor

#120 style: Input -> textfiled
  pages/orders/new.tsx
  types/orders.ts
Labels: 프론트, refactor

#122 fix: 각 페이지의 통신 실패시 에러대응
  components/Admin/marketList.tsx
  components/Api/Main.ts
  components/Api/Market.ts
  components/Api/index.tsx
  components/Main/cake/cakeList.tsx
  components/Market/marketProfile.tsx
  components/Shared/apiErrorAlert.tsx
Labels: fix

#128 fix: 린트 에러 (preview 수정)
  components/Mypage/mypageTitle.tsx
  components/Mypage/types.ts
  pages/index.tsx
  pages/mypage/enrollment/index.tsx
  pages/mypage/enrollment/success/index.tsx
  pages/mypage/orderlist/index.tsx
Labels: 프론트, fix

#131 feat: thread comment
  components/Orders/OfferComments.tsx
  components/Orders/Thread.tsx
  types/offer.ts
Labels: 프론트, feat, refactor

#138 refactor: 자잘한 오류 , 린트 에러 , 타입스크립트 분리 , 상수 분리 ( 2차 )
  .vscode/settings.json
  components/Admin/marketItem.tsx
  components/Admin/marketList.tsx
  components/Api/Main.ts
  components/Api/Market.ts
  components/Api/index.tsx
  components/Header/icon.tsx
  components/Header/index.tsx
  components/Main/cake/cakeItem.tsx
  components/Main/cake/cakeList.tsx
  components/Main/index.tsx
  components/Main/location/locationListItem.tsx
  components/Main/location/locationSelectBox.tsx
  components/Market/index.tsx
  components/Market/marketTitle.tsx
  constants/Api.ts
  constants/Main.ts
  pages/api/enrollments/index.tsx
  pages/main.tsx
  pages/market/[id].tsx
  public/icon.tsx
  types/Admin.ts
  types/Api.ts
  types/Main.ts
  types/Market.ts
  utils/numberWithCommas.ts
  utils/numberWithHyphen.ts
Labels: 프론트, refactor

#143 feat: 로그인 기능 추가
  components/Orders/OfferComments.tsx
  pages/orders/[id]/new-offer.tsx
  pages/orders/new.tsx
  utils/getAccessToken.ts
Labels: 프론트, feat

#147 fix: 상세페이지 애러 대응 (ver1)
  components/Orders/ImageSlider.tsx
  components/Orders/OfferComments.tsx
  hooks/useSelectOffer.ts
  pages/orders/[id]/index.tsx
Labels: 프론트, fix

#145 feat: access_token 기반 해더 변경
  components/Header/index.tsx
  utils/deleteAccessToken.ts
Labels: feat

#148 feat: 내 주문 리스트 api 연동
  components/Api/Enrollment.ts
  components/Api/Order.ts
  components/Mypage/enrollmentForm.tsx
  components/Mypage/post.tsx
  components/Mypage/types.ts
  pages/mypage/index.tsx
  pages/mypage/orderlist/index.tsx
  types/Api.ts
Labels: 프론트, feat

#151 fix: 메인 로그인 애러 대응
  pages/index.tsx
  pages/main.tsx
Labels: 프론트, fix

#152 feat: 로그아웃 구현
  components/Header/index.tsx
  utils/deleteAccessToken.ts
Labels: 프론트, feat, fix

#153 feat: login page -> main page
  components/Header/index.tsx
  components/Shared/apiErrorAlert.tsx
  pages/_app.tsx
  pages/index.tsx
  pages/login.tsx
  pages/main.tsx
  pages/mypage/enrollment/success/index.tsx
  pages/orders/new.tsx
Labels: 프론트, feat

#154 fix: header link
  components/Header/index.tsx
Labels: 프론트, fix

#156 fix: login issue
  pages/login.tsx
Labels: 프론트, fix

#157 fix: login issue
  pages/login.tsx
Labels: 프론트, fix

#163 feat: 지연님 수정사항 + 일부 로딩개선
  components/Api/Enrollment.ts
  components/Market/index.tsx
  pages/index.tsx
  pages/main.tsx
Labels: feat

#165 feat: 업체 등록 api 연동
  components/Mypage/enrollmentForm.tsx
Labels: 프론트, feat

#166 fix: 토큰 발급 코드 위치 변경
  components/Mypage/enrollmentForm.tsx
Labels: 프론트, fix

#162 feat: error message 연동
  components/Orders/OfferComments.tsx
  pages/orders/[id]/new-offer.tsx
Labels: 프론트, feat, fix

#167 fix: field name change
  components/Orders/OfferComments.tsx
Labels: 프론트, feat, fix

#168 fix: access token
  components/Orders/OfferComments.tsx
Labels: 프론트, fix

#169 fix: axios -> publicApi
  components/Orders/OfferComments.tsx
Labels: 프론트, fix

#170 feat: invalidateQueries
  components/Mypage/post.tsx
  components/Orders/OfferComments.tsx
  pages/mypage/orderlist/index.tsx
Labels: 프론트, feat

#172 feat: 업체 등록 후 재로그인
  components/Mypage/enrollmentForm.tsx
Labels: 프론트, feat, fix

#171 feat: 업체 상세 페이지를 SSG로 사전 로딩후 일정시간마다 변경되게 한다
  components/Market/index.tsx
  components/Orders/Thread.tsx
  pages/api/enrollments/index.tsx
  pages/main.tsx
  pages/market/[id].tsx
Labels: feat

#173 refactor: chakra ui (Mypage)
  components/Mypage/enrollmentForm.tsx
  pages/mypage/enrollment/index.tsx
Labels: 프론트, refactor, design

#174 fix: mypage and order
  components/Mypage/post.tsx
  hooks/useSelectOffer.ts
  pages/orders/[id]/new-offer.tsx
Labels: 프론트, fix

#179 feat: custom hook (error)
  components/Mypage/enrollmentForm.tsx
  components/Orders/OfferComments.tsx
  hooks/useHandleAxiosError.ts
  hooks/useSelectOffer.ts
  pages/main.tsx
  pages/orders/[id]/new-offer.tsx
Labels: 프론트, feat

#180 refactor: chakra ui - toast
  components/Mypage/enrollmentForm.tsx
  hooks/useSelectOffer.ts
  pages/orders/[id]/new-offer.tsx
  pages/orders/new.tsx
Labels: 프론트, feat, refactor

#181 feat: 예약된 주문 삭제 불가 토스트 적용
  components/Mypage/post.tsx
Labels: 프론트, feat

#184 refactor: order design
  components/Orders/CakeSelect.tsx
  hooks/useImageUpload.ts
  pages/_app.tsx
  pages/orders/new.tsx
Labels: 프론트, feat, refactor, design

#185 design: 메인페이지 & 해더의 디자인을 개선한다
  components/Header/index.tsx
  components/Main/cake/cakeItem.tsx
  components/Main/cake/cakeList.tsx
  components/Main/index.tsx
  components/Main/location/locationListItem.tsx
  components/Main/location/locationSelectBox.tsx
  constants/Main.ts
  public/icon.tsx
  public/theme/theme.ts
  types/Main.ts
Labels: feat, refactor, design

#187 refactor: order design
  components/Orders/DataTable.tsx
  pages/orders/[id]/index.tsx
  utils/orders.ts
Labels: 프론트, feat, refactor, design

#188 refactor: 게시글 삭제 로직 관련(마이페이지)
  components/Api/Order.ts
  components/Main/index.tsx
  components/Mypage/mypageTitle.tsx
  pages/_app.tsx
  pages/mypage/index.tsx
  public/images/cakeIcon.png
  public/images/shop.png
Labels: 프론트, refactor, design

#190 refactor: thread design change
  components/Orders/OfferComments.tsx
  components/Orders/Thread.tsx
  pages/orders/[id]/index.tsx
  types/orders.ts
Labels: 프론트, feat, refactor, design

#191 design: 업체 상세페이지의 디자인을 개선한다
  components/Main/cake/cakeItem.tsx
  components/Main/cake/cakeList.tsx
  components/Market/index.tsx
  components/Market/kakaoMaps.tsx
  components/Market/marketTitle.tsx
  components/Shared/headerTitle.tsx
  package-lock.json
  package.json
  pages/_document.tsx
  public/icon.tsx
  tsconfig.json
  types/Main.ts
Labels: 프론트, feat, design

#193 feat: 결제 개발
  README.md
  components/Orders/DataTable.tsx
  components/Orders/Thread.tsx
  hooks/useSelectOffer.ts
  package-lock.json
  package.json
  pages/orders/[id]/pay/index.tsx
  public/images/cash.png
  public/images/toss.png
Labels: 프론트, feat

#194 refactor: 린트 애러 해결, 애러 문구 상수화 및 타입 적용
  .eslintrc.json
  components/Api/Enrollment.ts
  components/Api/Order.ts
  components/Api/index.tsx
  components/Main/index.tsx
  components/Market/kakaoMaps.tsx
  components/Mypage/enrollmentForm.tsx
  components/Mypage/enrollmentInfo.tsx
  components/Mypage/mypageTitle.tsx
  components/Mypage/post.tsx
  components/Orders/OfferComments.tsx
  constants/errorMessages.ts
  hooks/useSelectOffer.ts
  pages/index.tsx
  pages/mypage/enrollment/success/index.tsx
  pages/mypage/index.tsx
  pages/orders/[id]/new-offer.tsx
  pages/orders/[id]/pay/index.tsx
  pages/orders/new.tsx
  utils/deleteAccessToken.ts
  utils/getMemberIdFromToken.ts
Labels: 프론트, feat, refactor, fix

#197 feat: order role 상세페이지 분기 고려
  components/Orders/ImageSlider.tsx
  components/Orders/OfferComments.tsx
  components/Orders/Thread.tsx
  components/Shared/headerTitle.tsx
  pages/index.tsx
  pages/orders/[id]/index.tsx
  pages/orders/[id]/new-offer.tsx
  pages/orders/[id]/pay/index.tsx
  pages/orders/new.tsx
  types/role.ts
  utils/getDecodeToken.ts
  utils/getMemberIdFromToken.ts
Labels: 프론트, feat

#198 refactor: 마이 주문 리스트 로직 관련(마이페이지)
  components/Mypage/countBar.tsx
  components/Mypage/filterBar.tsx
  components/Mypage/mypageTitle.tsx
  components/Mypage/notExist.tsx
  components/Mypage/post.tsx
  components/Mypage/types.ts
  pages/mypage/enrollment/index.tsx
  pages/mypage/enrollment/success/index.tsx
  pages/mypage/index.tsx
  pages/mypage/orderlist/index.tsx
  public/images/CalenderIcon.png
  public/images/grayCakeIcon.png
  types/orders.ts
Labels: 프론트, refactor, design

#202 feat: 로그인 환경변수 추가
  pages/main.tsx
Labels: 프론트, feat

#204 refactor: new order 버그 수정 및 삭제 기능 추가
  components/Orders/RemoveImageButton.tsx
  pages/orders/[id]/new-offer.tsx
  pages/orders/new.tsx
Labels: 프론트, feat, fix

#203 feat: 404 페이지 및 api 통신 페이지 작성
  components/Admin/adminMarketInfo/index.tsx
  components/Admin/marketList.tsx
  components/Error/index.tsx
  components/Main/cake/cakeList.tsx
  components/Market/index.tsx
  components/Shared/apiErrorAlert.tsx
  pages/404.tsx
  pages/_error.tsx
  public/icon.tsx
Labels: feat, design

#205 fix: thread and layout
  components/Orders/Thread.tsx
  pages/index.tsx
  pages/orders/[id]/new-offer.tsx
  pages/orders/new.tsx
  types/orders.ts
Labels: 프론트, refactor, fix

#206 refactor: 자잘한 오류 , 린트 에러 , 타입스크립트 분리 , 상수 분리 ( 3차 )
  .vscode/settings.json
  components/Admin/adminMarketInfo/index.tsx
  components/Admin/buttonContainer/deletedContainer.tsx
  components/Admin/buttonContainer/waitingContainer.tsx
  components/Admin/marketItem.tsx
  components/Admin/marketList.tsx
  components/Api/Main.ts
  components/Api/Market.ts
  components/Api/Order.ts
  components/Error/index.tsx
  components/Main/cake/cakeItem.tsx
  components/Main/cake/cakeList.tsx
  components/Main/header.tsx
  components/Main/index.tsx
  components/Main/location/locationListItem.tsx
  components/Main/location/locationSelectBox.tsx
  components/Market/index.tsx
  components/Shared/headerTitle.tsx
  components/Shared/kakaoMaps.tsx
  constants/Kakao.ts
  constants/Main.ts
  pages/_document.tsx
  types/Admin.ts
  types/Api.ts
  types/Main.ts
  types/Market.ts
  types/Shared.ts
Labels: 프론트, refactor

#207 refactor: 업체 정보 등록 로직 관련(마이페이지)
  components/Mypage/enrollmentForm.tsx
  components/Mypage/filterBar.tsx
  components/Mypage/mypageTitle.tsx
  constants/errorMessages.ts
  constants/seoulArea.ts
  hooks/useHandleAxiosError.ts
  pages/mypage/enrollment/index.tsx
  pages/mypage/enrollment/success/index.tsx
  pages/mypage/index.tsx
  pages/mypage/orderlist/index.tsx
  public/images/cameraIcon.png
Labels: 프론트, refactor, design

#210 refactor: 2차 배포 전 이슈 해결
  components/Admin/buttonContainer/approvedContainer.tsx
  components/Admin/buttonContainer/deletedContainer.tsx
  components/Admin/buttonContainer/waitingContainer.tsx
  components/Error/index.tsx
  components/Main/cake/cakeItem.tsx
  components/Main/cake/cakeList.tsx
  components/Main/index.tsx
  components/Main/location/locationListItem.tsx
  components/Main/location/locationSelectBox.tsx
  components/Mypage/enrollmentForm.tsx
  components/Mypage/notExist.tsx
  components/Mypage/post.tsx
  components/Orders/OfferComments.tsx
  components/Orders/Thread.tsx
  hooks/useHandleAxiosError.ts
  hooks/useSelectOffer.ts
  package-lock.json
  package.json
  pages/404.tsx
  pages/index.tsx
  pages/mypage/index.tsx
  pages/orders/[id]/index.tsx
  pages/orders/[id]/new-offer.tsx
  pages/orders/[id]/pay/fail/index.tsx
  pages/orders/[id]/pay/index.tsx
  pages/orders/[id]/pay/success/index.tsx
  pages/orders/new.tsx
  public/images/birthday-cake.png
  public/images/cake.png
  public/images/cash.png
  public/images/completedCake.png
  public/images/prgms.png
  public/images/toss.png
  styles/style.css
  types/offer.ts
Labels: 프론트, feat, refactor, chore, fix, design

#211 refactor: 업체 정보 등록 완료 로직 관련 (마이페이지)
  components/Mypage/enrollmentForm.tsx
  components/Mypage/successModal.tsx
  pages/mypage/enrollment/success/index.tsx
Labels: 프론트, refactor, design

#213 Refactor/95/bug fix
  .vscode/settings.json
  components/Main/cake/cakeList.tsx
  components/Main/index.tsx
  components/Main/location/locationSelectBox.tsx
  pages/_app.tsx
Labels: feat, refactor

#215 feat: comment format time
  components/Orders/OfferComments.tsx
  types/offer.ts
  utils/formatCommentDate.ts
Labels: 프론트, feat

#216 refactor: 디자인 & 사용성 반영 1차
  components/Admin/index.tsx
  components/Main/cake/cakeList.tsx
  components/Main/index.tsx
  components/Market/index.tsx
  components/Mypage/post.tsx
  components/Mypage/successModal.tsx
  components/Orders/OfferComments.tsx
  components/Shared/headerTitle.tsx
  hooks/useHandleAxiosError.ts
  hooks/useSelectOffer.ts
  pages/_app.tsx
  pages/mypage/index.tsx
  pages/orders/[id]/index.tsx
  pages/orders/[id]/new-offer.tsx
  pages/orders/[id]/pay/index.tsx
  pages/orders/new.tsx
Labels: feat

#220 feat: 2차 배포 전 주문페이지 디테일 개선
  components/Orders/OfferComments.tsx
  pages/orders/[id]/index.tsx
Labels: 프론트, feat, fix, design

#222 refactor: mypage rollback
  components/Mypage/enrollmentForm.tsx
  components/Mypage/successModal.tsx
Labels: 프론트, refactor

#226 fix: 로그인 문제 해결
  pages/main.tsx
Labels: 프론트, fix

#227 chore: ver2.01
  pages/main.tsx
Labels: chore

#228 Fix/224/error fix
  components/Main/index.tsx
  pages/admin/index.tsx
  pages/main.tsx
  pages/mypage/index.tsx
Labels: feat

#230 fix: 모달 안뜨는 이슈 해결
  components/Mypage/enrollmentForm.tsx
  components/Mypage/successModal.tsx
  pages/mypage/index.tsx
Labels: 프론트, fix

#231 fix: comment clear
  components/Main/index.tsx
  components/Orders/OfferComments.tsx
  pages/_app.tsx
  pages/orders/[id]/index.tsx
Labels: 프론트, fix

#233 fix: 문구 중복 해결
  pages/mypage/index.tsx
Labels: 프론트, fix

#234 fix: 메인페이지 undefined 변경
  constants/Main.ts
Labels: feat

#237 refactor: 내 주문 리스트 로직 관련 (마이페이지)
  components/Mypage/post.tsx
  pages/mypage/orderlist/index.tsx
  types/orders.ts
Labels: 프론트, refactor
