Repository prgrms-web-devcourse/team-7sung-heycake-fe, pull requests merged in 2023-02, with the labels that each got.

#9 chore: pr 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#10 chore: 차크라 UI 커스텀 색상 추가
  pages/_app.tsx
  public/theme/theme.ts
Labels: chore

#11 feat: 업체 상세 페이지 마크업
  components/Stores/icon.tsx
  components/Stores/index.tsx
  components/Stores/storetitle.tsx
  pages/stores/[id].tsx
  public/images/prgms.png
Labels: feat

#12 feat: 로그인 진입 페이지 마크업
  package-lock.json
  package.json
  pages/index.tsx
Labels: feat

#15 chore: package clean
  package-lock.json
  package.json
Labels: 프론트, chore

#19 chore: eslint 추가 설정
  .eslintrc.json
  components/Header/index.tsx
  components/Stores/index.tsx
  components/Stores/storetitle.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
Labels: 프론트, chore

#20 feat: Licence
  Licence
Labels: 프론트, feat

#22 feat: 메인 페이지 작성완료
  .vscode/settings.json
  components/Main/cakeItem.tsx
  components/Main/cakeMain.tsx
  components/Main/selectBox.tsx
  components/Main/types.ts
  package-lock.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/main.tsx
  pages/stores/[id].tsx
  public/images/completedCake.png
  public/theme/theme.ts
Labels: feat

#23 feat: 카카오 로그인 구현 - 인가 코드 받기
  pages/_app.tsx
  pages/index.tsx
  public/images/kakao_login_medium_wide.png
Labels: 프론트, feat

#24 feat: 마크업 작업 정리 및 일부 기능 추가
  components/Header/index.tsx
  components/Market/icon.tsx
  components/Market/marketProfile.tsx
  components/Market/marketTitle.tsx
  package-lock.json
  pages/market/[id].tsx
  pages/stores/[id].tsx
Labels: 프론트, feat, refactor

#27 chore: eslint airbnb
  .eslintrc.json
  package-lock.json
  package.json
  pages/_app.tsx
Labels: 프론트, chore

#29 feat: GitHub Action CI
  .github/workflows/ci-workflow.yml
  package.json
Labels: 프론트, feat

#35 !HOTFIX: ci
  .github/workflows/ci-workflow.yml
Labels: 프론트, fix

#33 feat: 마이페이지(메인) 마크업
  components/Main/cakeItem.tsx
  components/Main/cakeMain.tsx
  package-lock.json
  pages/_app.tsx
  pages/index.tsx
  pages/main.tsx
  pages/mypage/enrollment/index.tsx
  pages/mypage/index.tsx
  pages/mypage/orderlist/index.tsx
  public/theme/theme.ts
Labels: 프론트, feat

#25 feat: 상세페이지 마크업
  components/Orders/DataTable.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/orders/[id].tsx
  public/images/birthday-cake.png
  public/images/cake.png
Labels: 프론트, feat

#38 feat: 메인페이지 핵심기능 구현
  components/Main/cakeItem.tsx
  components/Main/cakeMain.tsx
  components/Main/locationListItem.tsx
  components/Main/locationSelectBox.tsx
  components/Main/selectBox.tsx
  components/Main/types.ts
  pages/_app.tsx
  pages/_document.tsx
Labels: feat

#42 chore: react-intersection-observer 설치
  package-lock.json
  package.json
Labels: feat

#47 Mock 데이터 통신을 위한 사전작업
  components/Api/getCakeList.tsx
  components/Api/index.tsx
  components/Api/mock/letteringGangbok.json
  components/Api/mock/letteringGangnam.json
  components/Api/mock/photoGangbok.json
  components/Api/mock/photoGangnam.json
  components/Main/cakeMain.tsx
  pages/api/.empty
  pages/api/orders.tsx
Labels: 프론트, feat

#44 feat: 관리자 페이지 마크업 및 기본 기능 생성
  components/Admin/index.tsx
  components/Admin/login.tsx
  components/Admin/marketItem.tsx
  pages/admin/index.tsx
  pages/admin/login.tsx
Labels: 프론트, feat

#48 feat: 마이페이지(업체 정보 등록) 마크업
  components/Mypage/enrollmentForm.tsx
  components/Mypage/mypageTitle.tsx
  constants/errorMessages.ts
  constants/seoulArea.ts
  package-lock.json
  package.json
  pages/mypage/enrollment/index.tsx
Labels: 프론트, feat

#52 feat: 업체 상세 페이지 MOCK API 연결
  components/Api/getCakeList.ts
  components/Api/getMarketDetail.ts
  components/Api/getMarketList.ts
  components/Api/mock/marketDetail.json
  components/Api/mock/marketList.json
  components/Market/marketProfile.tsx
  components/Market/marketProfileSkeleton.tsx
  components/Market/marketTitle.tsx
  next.config.js
  pages/api/enrollments/[id].tsx
  pages/api/enrollments/index.tsx
Labels: 프론트, feat

#60 feat: orders type
  types/orders.ts
Labels: 프론트, feat

#58 feat: thread mark up
  components/Orders/Thread.tsx
  pages/orders/[id].tsx
Labels: 프론트, feat

#56 feat: 관리자 페이지와 Mock API를 연동한다
  components/Admin/index.tsx
  components/Admin/marketItem.tsx
  components/Admin/marketList.tsx
  components/Api/mock/marketList.json
  pages/api/enrollments/index.tsx
Labels: 프론트, feat
